global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dev-cluster'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'k3s-server'
    static_configs:
      - targets: ['k3s-server:10250']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'k3s-agents'
    static_configs:
      - targets: 
        - 'k3s-agent-1:10250'
        - 'k3s-agent-2:10250'
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'rancher'
    static_configs:
      - targets: ['rancher:443']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_dev_service_type]
        action: keep
        regex: .+
      - source_labels: [__meta_docker_container_label_dev_service_name]
        target_label: service_name
      - source_labels: [__meta_docker_container_label_dev_service_type]
        target_label: service_type
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        regex: /(.*)
        replacement: ${1}

  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: /etc/kubeconfig/kubeconfig.yaml
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
        kubeconfig_file: /etc/kubeconfig/kubeconfig.yaml
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        kubeconfig_file: /etc/kubeconfig/kubeconfig.yaml
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
