issuer: http://argocd-dex:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

logger:
  level: "info"
  format: "json"

oauth2:
  responseTypes: ["code", "token", "id_token"]
  skipApprovalScreen: true

staticClients:
- id: argocd
  redirectURIs:
  - 'http://argocd.k3s.local:8088/auth/callback'
  name: 'ArgoCD'
  secret: argocd-secret

connectors:
- type: mockCallback
  id: mock
  name: Example
  config:
    username: "admin"
    userID: "admin"

enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leU.TZh5GdKu"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
