---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: database-monitoring-rules
  namespace: database
  labels:
    app: database-monitoring
    release: kube-prometheus-stack
spec:
  groups:
  - name: postgresql.rules
    interval: 30s
    rules:
    - alert: PostgreSQLDown
      expr: pg_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "PostgreSQL is down"
        description: "PostgreSQL database {{ $labels.instance }} is down for more than 1 minute."
        
    - alert: PostgreSQLTooManyConnections
      expr: sum by (instance) (pg_stat_database_numbackends) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL has too many connections"
        description: "PostgreSQL instance {{ $labels.instance }} has {{ $value }} connections (>80%)."
        
    - alert: PostgreSQLHighConnectionsUsage
      expr: sum by (instance) (pg_stat_database_numbackends) / pg_settings_max_connections * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL connection usage is high"
        description: "PostgreSQL instance {{ $labels.instance }} is using {{ $value }}% of available connections."
        
    - alert: PostgreSQLSlowQueries
      expr: avg by (instance) (rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m])) < 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL slow queries detected"
        description: "PostgreSQL instance {{ $labels.instance }} has slow query performance (fetch ratio: {{ $value }})."
        
    - alert: PostgreSQLDeadlocks
      expr: increase(pg_stat_database_deadlocks[1m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL deadlocks detected"
        description: "PostgreSQL instance {{ $labels.instance }} has {{ $value }} deadlocks."
        
    - alert: PostgreSQLHighDiskUsage
      expr: (pg_database_size_bytes / (1024^3)) > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PostgreSQL database size is large"
        description: "PostgreSQL database {{ $labels.datname }} on {{ $labels.instance }} is {{ $value }}GB."
        
  - name: mysql.rules
    interval: 30s
    rules:
    - alert: MySQLDown
      expr: mysql_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "MySQL is down"
        description: "MySQL database {{ $labels.instance }} is down for more than 1 minute."
        
    - alert: MySQLTooManyConnections
      expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL has too many connections"
        description: "MySQL instance {{ $labels.instance }} is using {{ $value }}% of available connections."
        
    - alert: MySQLHighQPS
      expr: rate(mysql_global_status_questions[5m]) > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL high queries per second"
        description: "MySQL instance {{ $labels.instance }} has {{ $value }} queries per second."
        
    - alert: MySQLSlowQueries
      expr: increase(mysql_global_status_slow_queries[1m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "MySQL slow queries detected"
        description: "MySQL instance {{ $labels.instance }} has {{ $value }} slow queries."
        
    - alert: MySQLInnoDBLogWaits
      expr: rate(mysql_global_status_innodb_log_waits[5m]) > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL InnoDB log waits"
        description: "MySQL instance {{ $labels.instance }} has {{ $value }} InnoDB log waits per second."
        
    - alert: MySQLReplicationLag
      expr: mysql_slave_lag_seconds > 30
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL replication lag"
        description: "MySQL slave {{ $labels.instance }} is {{ $value }} seconds behind master."
        
  - name: cloudbeaver.rules
    interval: 60s
    rules:
    - alert: CloudBeaverDown
      expr: up{job="cloudbeaver"} == 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "CloudBeaver is down"
        description: "CloudBeaver service {{ $labels.instance }} is down for more than 2 minutes."
        
    - alert: CloudBeaverHighResponseTime
      expr: http_request_duration_seconds{job="cloudbeaver"} > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "CloudBeaver high response time"
        description: "CloudBeaver instance {{ $labels.instance }} has response time of {{ $value }} seconds."
