---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: logging
data:
  opensearch.yml: |
    cluster.name: k3s-dev-cluster
    node.name: opensearch-node
    network.host: 0.0.0.0
    discovery.type: single-node
    plugins.security.disabled: true
    bootstrap.memory_lock: false
    
    # Index settings
    action.auto_create_index: true
    cluster.routing.allocation.disk.threshold_enabled: false
    
    # Performance settings
    indices.memory.index_buffer_size: 20%
    indices.fielddata.cache.size: 40%
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.1
        env:
        - name: discovery.type
          value: "single-node"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: bootstrap.memory_lock
          value: "false"
        - name: plugins.security.disabled
          value: "true"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: opensearch-config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: opensearch-config
        configMap:
          name: opensearch-config
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
      - name: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:2.11.1
        env:
        - name: OPENSEARCH_HOSTS
          value: "http://opensearch:9200"
        - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
          value: "true"
        ports:
        - containerPort: 5601
        resources:
          requests:
            memory: "512m"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: logging
spec:
  selector:
    app: opensearch-dashboards
  ports:
  - port: 5601
    targetPort: 5601
  type: ClusterIP
